### PR TITLE
highlight wordy with SpellLocal or SpellRare

### PR DESCRIPTION
**Pull request by sunaku**
Hello,

Currently, wordy words are highlighted with SpellBad, which is the same classification that the normal spellcheck feature uses most of the time.  As a result, it's difficult to know which highlighted words come from spellcheck and which come from wordy. :confused:  If wordy words were highlighted with SpellLocal or SpellRare instead, it would be easier to visually distinguish the two sources. :smiley_cat:

Thanks for your consideration.

### CODE REVIEW

**Comment by sunaku** [comment]
Patch attached, but it doesn't work as advertised in `:help spell-wordlist-format` :crying_cat_face:

**Comment by sunaku** [comment]
:book: Found the reason in `:help spell-RARE`, it's a matter of priority:

> Rare words are highlighted differently from bad words.  This is to be used for
> words that are correct for the language, but are hardly ever used and could be
> a typing mistake anyway.  When the same word is found as good it won't be
> highlighted as rare.

There's [an old Vim patch](https://www.mail-archive.com/vim_dev%40googlegroups.com/msg10482.html) to fix this priority but it seems lost to history. :sob:

**Comment by sunaku** [comment]
Good news!  NeoVim has been patched to make use of SpellRare in https://github.com/neovim/neovim/pull/2456.  So I have updated the patch in this pull request to enable the SpellRare change only for NeoVim by creating a new `/data-neovim` subfolder and storing the modified dictionaries therein. :cake:

**Comment by reedes** [comment]
Thanks. I'll take a look at this later this week.

**Comment by sunaku** [comment]
:+1: Sounds good, and @jalvesaq and I have added further refined the code in this pull request. :neckbeard:

**Pull request merged**
